### ISSUE TITLE
DB schema

### ISSUE THREAD

**Issue by alrud0x0** [alrud0x0/stock_game#7]
#### 어드민
- 인증 no(암호화)

#### 사용자
- 사용자 unique ID 
- 사용자 ID
- passwd(암호화)
- 닉네임

#### 포인트
- 사용자 id ( 사용자 > 사용자별 Id)
- 게임 id (게임 > 게임별 id)
- 참여포인트 
- 순위권포인트

#### 주식정보
- 주식을 구분할 unique ID (주식id로 하면될듯)
- 현재가격 : 매일 update -> 업데이트 주기 필요

#### 게임(히스토리)
- 게임별 id : 회차로 구분
- 게임 start date
- 게임 end date

#### 게임별 주식
- 게임별 Id(게임 > 게임별 Id)
- 주식 id (주식정보 > 주식id)
- 주식 명 (주식정보 > 주식명)
- 금요일 종가 (주식정보 > 현재가)
- 현재가 (주식정보 > 현재가)
- 현재가 대비 상승 퍼센트

#### 사용자별 게임참여
- 게임별 id(게임 > 게임별 id)
- 사용자 id(사용자 > 사용자별 id)
- 주식 id(주식정보 > 주식 id)
- 이유

**Comment by alrud0x0** [comment]
### 시나리오
#### 주식 정보 가져오기(서버 자동수행)
* 최초에 한번 쫙 가져오는 것 생성 (api 같은거 있는지 알아봐야함)
* 주기적으로 가격 정보를 가져온다. (주기는 정해야함)
* 있는 주식은 UPDATE, 최근 상장했다면 CREATE 
* 상폐된 것은 DELETE

#### 사용자가 가입을 함
* SELECT : 어드민 테이블의 인증번호가 맞는지 확인 (코드에 박아넣을까?)
* CREATE : 사용자 테이블에 정보 생성

#### 사용자 랭킹/점수 조회
* SELECT : 포인트 테이블에서 사용자 id로 가져와서 sum 한 값 노출

#### upcoming 게임 생성(어드민이?, 자동으로?)
* CREATE : 게임테이블에 정보 생성, 게임id는 startdate, enddate로 자동 생성

#### upcoming 게임 참여 (금요일 장 종료 이후 가능, 월요일 장 시작 전까지 가능)
* CREATE : 게임별 주식 테이블에 정보 생성, 사용자별 게임참여 테이블에 정보 생성
* UPDATE : 현재가(api 사용 가능한지 확인 필요), 현재가 대비 상승 퍼센트(현재가와 금요일 종가로 자동 계산되게 한다.) => 얼마만에 한번씩 update 할 건지 확인 필요
* UPDATE / DELETE : 사용자가 투표한 내용을 수정하거나 투표 취소했을 때, 사용자별 게임참여 테이블에 반영

#### 진행중 게임 조회(전체 리스트)
* SELECT : 게임별 주식 테이블에서 게임별 Id 로 리스트 가져와서 노출(주식명, 금요일 종가, 현재가, 현재가 대비 퍼센트), 사용자별 게임참여 테이블에서 게임별id-주식 Id로 리스트 sum 값 노출(투표수)

#### 진행중 게임 조회(각 주식 별 게임 참여 리스트)
* SELECT : 사용자별 게임참여 테이블에서 게임별id-주식 Id로 사용자 리스트 노출, 게임별id-주식id-사용자id로 각 사용자별 투표 이유 노출

**Comment by alrud0x0** [comment]
<img width="1023" alt="스크린샷 2020-01-13 오후 3 43 17" src="https://user-images.githubusercontent.com/44351768/72236781-89ac2a80-361b-11ea-88cc-e6cc5d198afb.png">


CREATE TABLE `users` (
  `id` int PRIMARY KEY,
  `user_id` varchar(255),
  `passwd_hash` varchar(255),
  `nickname` varchar(255)
);

CREATE TABLE `points` (
  `game_id` int,
  `user_id` int,
  `attand_point` int,
  `winning_point` int
);

CREATE TABLE `stocks` (
  `id` int PRIMARY KEY,
  `name` varchar(255),
  `price` int
);

CREATE TABLE `games` (
  `id` int PRIMARY KEY AUTO_INCREMENT,
  `create_date` timestamp,
  `end_date` timestamp
);

CREATE TABLE `game_stocks` (
  `game_id` int,
  `stock_id` int,
  `stock_name` int,
  `last_price` int,
  `current_price` int,
  `percent` long
);

CREATE TABLE `user_games` (
  `game_id` int,
  `user_id` int,
  `stock_id` int,
  `reason` varchar(255)
);

ALTER TABLE `points` ADD FOREIGN KEY (`game_id`) REFERENCES `games` (`id`);

ALTER TABLE `points` ADD FOREIGN KEY (`user_id`) REFERENCES `users` (`id`);

ALTER TABLE `game_stocks` ADD FOREIGN KEY (`game_id`) REFERENCES `games` (`id`);

ALTER TABLE `game_stocks` ADD FOREIGN KEY (`stock_id`) REFERENCES `stocks` (`id`);

ALTER TABLE `game_stocks` ADD FOREIGN KEY (`stock_name`) REFERENCES `stocks` (`name`);

ALTER TABLE `user_games` ADD FOREIGN KEY (`game_id`) REFERENCES `games` (`id`);

ALTER TABLE `user_games` ADD FOREIGN KEY (`user_id`) REFERENCES `users` (`id`);

ALTER TABLE `user_games` ADD FOREIGN KEY (`stock_id`) REFERENCES `stocks` (`id`);

**Comment by alrud0x0** [comment]
## 수정
<img width="700" alt="스크린샷 2020-01-14 오전 10 18 08" src="https://user-images.githubusercontent.com/27203639/72305507-5ae39200-36b7-11ea-9607-7ba1af7db71b.png">

```
Table users as U {
  id int [pk, increment]
  passwd varchar
  name varchar
  point long
}

Table stocks as S {
  id int [pk, increment]
  name varchar
  price long
}

Table user_games as UG {
  user_id int [ref: > U.id] // inline relationship (many-to-one)
stock_id int [ref: > S.id] // inline relationship (many-to-one)
  game_id int [ref: > G.id] // inline relationship (many-to-one)
  why varchar
}

Table stock_games as SG {
  stock_id int [ref: > S.id] // inline relationship (many-to-one)
  game_id int [ref: > G.id] // inline relationship (many-to-one)
  last_price long
  current long
}

Table games as G {
  id int [pk, increment] // auto-increment
  start datetime
}
```

**Comment by mr-sense** [comment]
한 유저의 한 게임당 선택할 수 있는 stock 은 3개 한정

**Comment by alrud0x0** [comment]
## 게임 기능정리

### 공통
* 주식 별 보팅한 정보(사용자/이유)를 조회할 수 있다.
* 페이징이 가능하다. (=> default 정렬 기준은 voting count 많은 순)
* 내가 보팅한 주식정보는 정렬기준에 상관없이 상위에 보여진다. (checkbox로 가능/해제 할 수 있도록?)

***

### 현재 게임 테이블
#### 보팅 가능 상태 (금 오후 10시 ~ 월 오전 8시)
* 금 오후 10시에 새로운 게임이 생성된다.
* 주식 정보는 금요일 오후 3시 30분의 정보로 보여준다.
* 사용자별 3개까지 보팅이 가능하다.

#### 보팅 불가, 조회만 가능 (월 오전 8시 ~ 금 오후 3시 30분)
* 장 시작 전 / 장 끝난 후 가격정보가 업데이트 된다.
* 업데이트 된 가격 정보에 따라 랭킹이 갱신된다.

#### 보팅 불가, 조회만 가능, 업데이트 없음 상태 (금 오후 3시 30분 ~ 금 오후 10시)
* 현재 게임의 최종 결과 조회 가능
* 주식 리스트 정렬은 상승률 순 정렬

***

### 지난 게임 테이블
#### 게임 리스트
* 지난 게임 리스트를 볼 수 있다.

#### 게임 리스트 > 자세히 보기
* 각 게임 차수(id) 별 보팅된 주식 리스트를 조회할 수 있다.
* 각 게임 차수 기간동안의 각 주식 별 상승률을 알 수 있다. (월 장 시작전 가격정보 / 금 장 마감 후 가격 정보가 필요)

**Comment by mr-sense** [comment]
1. 게임의 컬럼명 오더링 기능을 상승률 하나로만 제한하자
  - 이유: 순위는 결국 상승률만 따진다. 그 외의 오더링은 의미 없지 않나
  - 별개로 스톡을 선택하게 하는 동작에서는 이름순, 가격순, 등 오더링이 가능해야 한다 + like 검색도

2. 1번으로 기능을 제한하게 되면, 현재 디비 구조에서 나의 게임테이블만 하나 더 추가하고 그 테이블은 매일 등수를 업데이트 친다. (요건 설명이 더 필요할듯)

**Comment by alrud0x0** [comment]
#### 1. 오더링 상승률로만 제한하는 것 이견없음
- API 결과로 상승률을 계산해서 줄 것인지? 오더링 기준으로만 삼을것인지? (기존에는 front단에서 계산하기로 했었음)
- 상승률 정렬 요청을 위한 파라미터 값 필요할 듯 <= 상승률 정렬은 게임 진행중에만 가능하니까 항상 계산하지 않아도 될 듯.

#### 2. 내 등수 테이블
- 어떻게 업데이트 할건지? : 주식별 > 보팅 정보의 userId별 > 등수 테이블 업데이트?
- 내 등수 보기 API를 따로 둘것인지, 게임 테이블 정보 API 결과에 포함시킬것인지?

**Comment by mr-sense** [comment]
2-1. 종가 로 일단위 주식 정보 업데이트시에 게임스톡사용자 테이블을 업데이트 치려고 함
2-2 내 등수보기api 라기 보다 게임의 내정보 보기 api 라는 표현으로 api지원할 예정
  /api/v1/games/1/users/1
  /api/v1/games/1/datas 와는 별도의 api 라는 의미

**Comment by mr-sense** [comment]
정리
<img width="582" alt="스크린샷 2020-03-06 오후 5 02 44" src="https://user-images.githubusercontent.com/27203639/76064154-6de65480-5fcc-11ea-9729-6c55cef4a5c9.png">

스크립트: https://github.com/alrud0x0/stock_game/blob/master/backend/script/init_stock.sql

```
// Creating tables
Table users as U {
  id int [pk, increment]
  name varchar
  passwd varchar
  email varchar
  reward long
  token varchar
}

Table games as G {
  id int [pk, increment] // auto-increment
  date datetime
  active int
}

Table stocks as S {
  id int [pk, increment]
  code varchar
  name varchar
  price long
  lastUpdate datetime
}

Table gamedata as GD {
  id int [pk, increment]
  gameId int [ref: > G.id] // inline relationship (many-to-one)
  stockId int [ref: > S.id] // inline relationship (many-to-one)
  stockCode varchar
  stockName varchar
  start int
  current int
  vote int
  rank int
}

Table user_gamedata as UGD {
  id int [pk, increment]
  userId int [ref: > U.id] // inline relationship (many-to-one)
  gameId int [ref: > G.id] // inline relationship (many-to-one)
  gamedataId int [ref: > GD.id] // inline relationship (many-to-one)
  reason varchar
}
```

TODO:
  - 협의 완료되면 wiki 로 옮길 예정

**Comment by alrud0x0** [comment]
이견 없습니다!!!
우선 저대로 하면 https://github.com/alrud0x0/stock_game/issues/7#issuecomment-593873970 기능은 다 가능해 보임
